### ISSUE TITLE
Codeception CodeCoverage

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii2-app-advanced#126]
Hey,

I was experimenting with code coverage. Wanted to add coverage info to our project which is covered by tests. I've installed empty advanced application template first to test the coverage and couldn't make it work. CodeCoverage works great in app-basic. Wondering why I can't get it to work in advanced template. Tried all possible things and settings.

Here is my condeception.yml config (P.S. runnning codeception and webserver locally)
````
include:
  - codeception/common
  - codeception/console
  - codeception/backend
  - codeception/frontend

paths:
  log: codeception/_output

settings:
  colors: true

coverage:
  enabled: true
  whitelist:
    include:
      - ../backend/controllers/*
      - ../backend/models/*
      - ../common/models/*
      - ../console/controllers/*
      - ../console/models/*
      - ../frontend/controllers/*
      - ../frontend/models/*
  blacklist:
    include:
      - ../backend/assets/*
      - ../backend/config/*
      - ../backend/runtime/*
      - ../backend/views/*
      - ../backend/web/*
      - ../common/config/*
      - ../common/mail/*
      - ../common/widgets/*
      - ../console/config/*
      - ../console/migrations/*
      - ../console/runtime/*
      - ../frontend/assets/*
      - ../frontend/config/*
      - ../frontend/runtime/*
      - ../frontend/views/*
      - ../frontend/web/*
      - ../vendor/*
      - ../tests/*
````
Running command `codecept run --coverage-html`
I always get the following output:
![Codeception Output](http://i.imgur.com/xcWGg6D.jpg)

As you can see from the image whitelist works great, but no coverage report. Html coverage in _output also reports 0s.
