### ISSUE TITLE
Codeception tests & \Yii::$container problem

### ISSUE THREAD

**Issue by jarekkozak** [yiisoft/yii2-app-advanced#15]
Hi,
I found strange behavior during  tests execution.  I defined class implementation using \Yii::$container like this:
```
\Yii::$container->set('\common\src\dict\ICarOwnerDictionary','\common\src\dict\CarOwnerDictionary');
```
in
```
 common/config/bootstrap.php
```
everything works ok until i try to run backend/functional tests. It is simple Cept test where I try to display page which gets dictionary implementation from \Yii::$container and display entries.

And there is the problem:
1. If I run backend application works perfect (in browser).
2. If I execute only functional test for backend - works fine
3. If I execute the whole tests - does not work.  There is empty \Yii:$container (debugged).

I found workaround, simply move 'common' test execution at the end - in tests/codeception.yml like this
```
include:
  - codeception/backend
  - codeception/frontend
  - codeception/console
  - codeception/common

paths:
  log: codeception/_output

settings:
  colors: true

``` 
After this change works perfect. It looks like only general  _bootstrap file is executed once at the beginning and testing 'common' destroys \Yii:$container.

I spent a while (long while) and I only found above workaround, maybe I did something wrong? Any idea? 
Regards,
Jarek
