### ISSUE TITLE
Acceptance Test from the box

### ISSUE THREAD

**Issue by azjoss** [yiisoft/yii2-app-advanced#279]
### What steps will reproduce the problem?
Acceptance test from the box fails because browser does not load page/url where App starts

my root `codeception.yml`
```
include:
    - common
    - frontend
    - backend
paths:
    log: console/runtime/logs
settings:
    colors: true
```

my frontend `codeception.yml`
```
namespace: frontend\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'

```
my frontend `acceptance.suit.yml`
```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://localhost:4444
            browser: firefox
        - Yii2:
            part: init
```

Selenium is ran on `localhost:4444`
Server is ran  by `./yii_test serve -t=frontend/web`

### What's expected?
passed successful

### What do you get instead?
I get next

```
Frontend\tests.acceptance Tests (1) --------------------------------------------------------------
✖ HomeCest: Check home (0.60s)
---------------------------------------------------------------------------------------------------
```

### Additional info
Screenshot of test's failure
![frontend tests acceptance homecest checkhome fail](https://user-images.githubusercontent.com/19776110/27140617-ae73a53e-512e-11e7-8f72-e68b0bedf2a7.png)

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| Codeception | 2.3.3
| PHP version      | 7.0.15
| Selenium           | 3.4.0
| geckodriver      | 0.17.0
| Operating system | Sierra 10.12.5
