### ISSUE TITLE
Add phpmyadmin or adminer image to docker-compose.yml

### ISSUE THREAD

**Issue by devellopah** [yiisoft/yii2-app-advanced#443]
Would you please add one of this guys, so one can tinker with database. You can add something like this to the bottom of **docker-compose.yml**
```
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
```
