### ISSUE TITLE
docker is not working

### ISSUE THREAD

**Issue by mansourcodes** [yiisoft/yii2-app-advanced#495]
### What steps will reproduce the problem?
I have created an `admin and api ` foulders instead of `frontend and backend `
then I tried  to run docker `docker-compose.yml` by using the command `docker-compose up`

### What do you get instead?

Console error:

```
salamat-web alnassre$ docker-compose up -d
Building api

Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 362, in ensure_image_exists
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: api>, {'message': 'Cannot locate specified Dockerfile: ./api/Dockerfile'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[86493] Failed to execute script docker-compose
```

### Additional info

  `docker-compose.yml`

```
version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

```

<img width="232" alt="Screen Shot 2021-02-12 at 12 58 03 PM" src="https://user-images.githubusercontent.com/3064487/107754029-f3709980-6d31-11eb-8e8d-69bd4403df98.png">

| Yii version   yii2-app-advanced    |
| PHP version      |
| Operating system : macbook ios |

**Comment by mansourcodes** [comment]
## Other try
```
version: '3.2'

services:
  admin:
    build: admin
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  api:
    build: api
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

```

## Error:

```
salamat-web alnassre$ docker-compose up -d
Building api

Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 362, in ensure_image_exists
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: api>, {'message': 'Cannot locate specified Dockerfile: Dockerfile'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[87299] Failed to execute script docker-compose
```

**Comment by mansourcodes** [comment]
I found the problem, the `api` folder does not have a `Dockerfile`.

It's works with only admin or other subdomains except for the API.

**How can I make the API also working on the docker container?**

**Comment by samdark** [comment]
@schmunk42 would you please take a look at the issue?

**Comment by schmunk42** [comment]
Can you post your `Dockerfile` in `api` ?
What's the output of `docker-compose logs api`?

**Comment by mansourcodes** [comment]
### worked 
after coped `Dockerfile` in `api` contain 

```
FROM yiisoftware/yii2-php:7.2-apache

# Change document root for Apache
RUN sed -i -e 's|/app/web|/app/api/web|g' /etc/apache2/sites-available/000-default.conf
```

`docker-compose.yml`file 

```
version: '3.2'

services:
  admin:
    build: admin
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  clinic:
    build: clinic
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  api:
    build: api
    ports:
      - 22080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

```

console 

```
>>>>$ docker-compose logs api
Attaching to salamat_api_1
api_1     | usermod: no changes
api_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.5. Set the 'ServerName' directive globally to suppress this message
api_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.5. Set the 'ServerName' directive globally to suppress this message
api_1     | [Tue Feb 16 10:09:46.658498 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
api_1     | [Tue Feb 16 10:09:46.658602 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
api_1     | 172.21.0.1 - - [16/Feb/2021:10:09:57 +0000] "GET / HTTP/1.1" 404 361 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
api_1     | 172.21.0.1 - - [16/Feb/2021:10:09:58 +0000] "GET /favicon.ico HTTP/1.1" 200 617 "http://localhost:22080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
api_1     | 172.21.0.1 - - [16/Feb/2021:10:10:01 +0000] "GET /clinics HTTP/1.1" 404 360 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
api_1     | 172.21.0.1 - - [16/Feb/2021:10:10:06 +0000] "GET /v1/clinics HTTP/1.1" 500 6904 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
api_1     | 172.21.0.1 - - [16/Feb/2021:10:10:14 +0000] "GET /v1/doctors HTTP/1.1" 500 6904 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
api_1     | [Tue Feb 16 10:10:45.009344 2021] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
```

**Comment by schmunk42** [comment]
```
api_1     | 172.21.0.1 - - [16/Feb/2021:10:09:57 +0000] "GET / HTTP/1.1" 404 361 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
```

Do you have an `index.php` in your `api/web` folder?
You should at least be able to open the root URL.

**Comment by mansourcodes** [comment]
we have a version folder where the doctors and clinics controller are on it.

exampel : http://localhost:22080/v1/doctors

```
<response>
<name>Database Exception</name>
<message>SQLSTATE[HY000] [2002] No such file or directory</message>
<code>2002</code>
<type>yii\db\Exception</type>
<file>/app/vendor/yiisoft/yii2/db/Connection.php</file>
<line>637</line>
...
```

## I think the database connection is lost

main-local.php

```
<?php
return [
    'components' => [
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost;dbname= yii2advanced',
            'username' => 'yii2advanced',
            'password' => 'secret',
            'charset' => 'utf8',
            'tablePrefix' => '',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
    ],
];

```

**Comment by schmunk42** [comment]
You are connecting to `localhost`, usually this is `db` in a Docker context.
Moreover your `dbname` has a leading space.

**Comment by mansourcodes** [comment]
### Thanks, Every thing worked Great 

the database was `mysql` on my **docker-compose.yml**.

finally dsn on  **main-local.php:**
`            
'dsn' => 'mysql:host=mysql;dbname=yii2advanced',
`

 I also added **phpmyadmin**.
**docker-compose.yml:**

```
version: '3.2'

services:
  admin:
    build: admin
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  clinic:
    build: clinic
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  api:
    build: api
    ports:
      - 22080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: yii2advanced
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M


```


for any subdomain, it must contain `Dockerfile`

```
FROM yiisoftware/yii2-php:7.2-apache

# Change document root for Apache
RUN sed -i -e 's|/app/web|/app/api/web|g' /etc/apache2/sites-available/000-default.conf
```

I hope this helped any one else 😄
