### ISSUE TITLE
Loading config file returns true instead of config file content

### ISSUE THREAD

**Issue by ChewieWookie** [yiisoft/yii2-app-advanced#565]
### What steps will reproduce the problem?
- In main codeception.yml add include statement to another module containing tests using Yii2 module
- Have at least one test class with 2 test cases inside
- Run codeception using `php /app/vendor/bin/codecept run Unit,*::Unit`

### What's expected?
With each test content of config file is loaded properly

### What do you get instead?
the result of line `$config = require($this->configFile);' is true instead of array with configuration.

### Additional info
Content of main `codeception.yml` file:
```
support_namespace: Support
include:
    - modules/db
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
settings:
    colors: true 
``` 

Content of module `codeception.yml' file:
```
namespace: modules\db
support_namespace: Support
bootstrap: _bootstrap.php
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
modules:
    config:
        Yii2:
            configFile: config/test.php
```

Content of 'suite.yml' file:
```
actor: UnitTester
modules:
    enabled:
        - Asserts
        - Yii2:
            part: ['orm']
step_decorators: ~
```

Test cases:
``` 
public function testCreateAndFind(){
        //given
        $model = new RequisitionDb();
        $model['order_number'] = '1111';
        //when
        $result = $model->save();
        $found = RequisitionDb::findOne(['id'=> $model->id]);
        //then
        $this->assertNotNull($found);
    }

    public function testDelete(){
        //given
        $model = new RequisitionDb();
        $model['order_number'] = '1111';
        $model->save();
        $id = $model->id;
        //when

        $model -> delete();
        //then
        $found = RequisitionDb::findOne($id);
        $this->assertNull($found);
    }
```
