### ISSUE TITLE
Nowrap for grid view

### ISSUE THREAD

**Issue by YaroslavShapoval** [yiisoft/yii2-app-advanced#65]
[Yii2 issue #8771](https://github.com/yiisoft/yii2/issues/8771)

```css
.grid-view th {
    white-space: nowrap;
}
```

This rule is not necessary for all columns and it's probably not necessary for the header line. The only thing this parameter must be set for certain cells, such as, ActionColumn.

I propose to add a helper class 'text-nowrap' and add it to the cells if necessary.

**backend/web/css/site.css** and **frontend/web/css/site.css**
```css
.text-nowrap {
    white-space: nowrap;
}
```

**common/confog/bootstap.php**
```php
\Yii::$container->set('yii\grid\ActionColumn', [
    'contentOptions' => [
        'class' => 'text-nowrap'
    ]
]);
```

**Comment by SilverFire** [comment]
The use case is valid, but i'm worried about changes in `common/confog/bootstap.php`
I think we should fix the bug with CSS only.

@yiisoft/core-developers what do you think?

**Comment by YaroslavShapoval** [comment]
I don't remember the exact details, but I think that this option might work
```css
.grid-view td {
    white-space: nowrap;
}
```
